import React from 'react'
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog"
import { Button } from '@/components/ui/button'
import { SessionDetail } from '../medical-agent/[sessionId]/page'
import moment from 'moment'
import { Dot } from 'lucide-react'

type props = {
    record: SessionDetail
}

function ViewReportDialog({ record }: props) {
    return (
        <Dialog>
            <DialogTrigger>
                <Button variant="ghost" size="sm">View Report</Button>
            </DialogTrigger>
            <DialogContent className="max-h-[80vh] overflow-y-auto">
                <DialogHeader>
                    <DialogTitle asChild>
                        <h2 className='text-center text-4xl'>Medical AI Voice Agent Report</h2>
                    </DialogTitle>
                    <DialogDescription asChild>
                        <div>
                            <div className='mt-10'>
                                <h2 className='font-bold text-blue-400 text-xl ml-2'>Session info</h2>
                                <p className='text-blue-400 text-lg mt-0'>___________________________________________________________</p>
                                <div className='grid grid-cols-2 mt-5 pt-0'>
                                    <h2><span className='font-bold'>Doctor: </span>{record?.selectedDoctor?.specialist}</h2>
                                    <h2><span className='font-bold'>User:</span> Anonymous</h2>
                                    <h2><span className='font-bold'>Cunsulted On:</span> {record?.createdon.slice(0, 25)}</h2>
                                    <h2><span className='font-bold'>Agent: </span>{record?.selectedDoctor?.specialist} AI</h2>
                                </div>


                                <h2 className='font-bold text-blue-400 text-xl ml-2 mt-5'>Chief Complaint</h2>
                                <p className='text-blue-400 text-lg mt-0 pt-0'>___________________________________________________________</p>
                                <div className='grid grid-cols-2 mt-5'>
                                    <h2>i have back pain</h2>
                                </div>

                                <h2 className='font-bold text-blue-400 text-xl ml-2'>Summary</h2>
                                <p className='text-blue-400 text-lg mt-0'>___________________________________________________________</p>
                                <div className='grid grid-cols-2 mt-1'>
                                    <p className='pt-0'>summary...</p>
                                </div>

                                <h2 className='font-bold text-blue-400 text-xl ml-2 mt-5'>Symptoms</h2>
                                <p className='text-blue-400 text-lg mt-0'>___________________________________________________________</p>
                                <div className='grid grid-cols-2 mt-5'>
                                    <h2>.</h2>
                                    <h2>.</h2>
                                </div>
                                <h2 className='font-bold text-blue-400 text-xl ml-2'>Duration & severity</h2>
                                <p className='text-blue-400 text-lg mt-0'>___________________________________________________________</p>
                                <div className='grid grid-cols-2 mt-5'>
                                    <h2><span className='font-bold'>Duration: </span>report</h2>
                                    <h2><span className='font-bold'>Severity: </span>report</h2>
                                </div>

                                <h2 className='font-bold text-blue-400 text-xl ml-2'>Medication Mentioned</h2>
                                <p className='text-blue-400 text-lg mt-0'>___________________________________________________________</p>
                                <div className='grid grid-cols-2 mt-5'>
                                    <h2><Dot/>first</h2>
                                    <h2><Dot/>second</h2>
                                </div>

                                <h2 className='font-bold text-blue-400 text-xl ml-2'>Recommendations</h2>
                                <p className='text-blue-400 text-lg mt-0'>___________________________________________________________</p>
                                <div className='grid grid-cols-2 mt-5'>
                                    <h2><Dot/>first tip</h2>
                                    <h2><Dot/> second tip</h2>
                                </div>

                                <p className='text-gray-400 mt-0'>_____________________________________________________________________________</p>
                                <h2 className='text-sm'>This Report was generated by an AI medical agentfor information purpose only.</h2>

                            </div>

                        </div>
                    </DialogDescription>
                </DialogHeader>
            </DialogContent>
        </Dialog>
    )
}

export default ViewReportDialog
